<?php

/**
 * @file
 * Image segmentation module
 */

/**
 * Implements hook_menu().
 * Drupal menus allow urls to be used as function calls, giving Drupal gets much
 * of its power and flexibility.
 * See https://api.drupal.org/api/drupal/modules!system!system.api.php/function/hook_menu/7
 */

function image_segmentation_menu()
{
    return array(
        'admin/islandora/segmentation' => array(
            'title' => 'Image Segmentaion Module',
            'description' => 'Configure the Image Segmentation solution pack.',
            'page callback' => 'drupal_get_form',
            'access arguments' => array('administer site configuration'),
            'page arguments' => array('image_segmentation_admin'),
            'file' => 'includes/admin.form.inc',
            'type' => MENU_NORMAL_ITEM,
        ),
    );
}

/**
 * Implements hook_theme().
 */
function image_segmentation_theme($existing, $type, $theme, $path)
{
    return array(
        'image_segmentation_segment' => array(
            'file' => 'theme/theme.inc',
            'template' => 'theme/image-segmentation-segment',
            'pattern' => 'image_segmentation_sidebar__',
            'variables' => array('object' => NULL),
        ),
    );
}
/**
 * Implements hook_cmodel_pid_islandora_ingest_steps().
 */
function image_segmentation_islandora_segmentedImageCModel_islandora_ingest_steps(array $form_state)
{
    return array(
        'image_segmentation_upload_segment' => array(
            'weight' => 10,
            'type' => 'form',
            'form_id' => 'image_segmentation_upload_segment_form',
            'module' => 'image_segmentation',
            'file' => 'includes/upload_segment.form.inc',
        ),
    );
}

/**
 * Implements hook_islandora_view_object().
 */
function image_segmentation_islandora_segmentedImageCModel_islandora_view_object(AbstractObject $object, $user, $page_number)
{
    $output = theme('image_segmentation_segment', array('object' => $object));
    return array('' => $output);
}

/**
 * Implements hook_islandora_required_objects().
 */
function image_segmentation_islandora_required_objects(IslandoraTuque $connection)
{
    $module_path = drupal_get_path('module', 'image_segmentation');
    // Image segmentation content model
    $content_model = $connection->repository->constructObject('islandora:segmentedImageCModel');
    $content_model->owner = 'fedoraAdmin';
    $content_model->label = 'Segmented Image Model';
    $content_model->models = 'fedora-system:ContentModel-3.0';

    // DS-COMPOSITE-MODEL datastream
    $datastream = $content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
    $datastream->label = 'DS-COMPOSITE-MODEL';
    $datastream->mimetype = 'application/xml';
    $datastream->setContentFromFile("$module_path/xml/content_models/image_segmentation_ds_composite_model.xml", FALSE);
    $content_model->ingestDatastream($datastream);

    return array(
        'image_segmentation' => array(
            'title' => 'Image Segmentation',
            'objects' => array(
                $content_model,
            )
        )
    );
}

/**
 * Alter newspaper ingest forms
 */

function islandora_newspaper_batch_form_alter(&$form, &$form_state, $form_id) {

  switch ($form_id)  {
    case 'islandora_newspaper_batch_form':
      $form['generate_extracted_segments'] = array(
        '#type' => 'checkbox',
        '#title' => t('Generate extracted segments'),
        '#weight' => 0,
        '#description' => t('Determine whether the articles being ingested are supposed to get derivatives generated right away or not'),
      );
      if (isset($form['actions']['submit'])) {
        $form['#submit'][] = 'generate_extracted_segments_handler_function';
      }
      break;
    case 'islandora_paged_content_upload_pdf_form':
      $form['generate_extracted_segments'] = array(
        '#type' => 'checkbox',
        '#title' => t('Generate extracted segments'),
        '#weight' => 0,
        '#description' => t('Determine whether the article being ingested is supposed to get derivatives generated right away or not'),
      );
      if (isset($form['actions']['submit'])) {
        $form['#submit'][] = 'generate_extracted_segments_handler_function';
      }
      break;
  }

  return $form;
}

function generate_extracted_segments_handler_function($form, &$form_state) {
  drupal_set_message(t('Form submitted'));
}

